// Generated by CoffeeScript 1.8.0
(function() {
  var container, msnry;

  container = document.getElementById('masonry');

  if (container != null) {
    msnry = new Packery(container, {
      itemSelector: '.tile',
      columnWidth: '.sizer',
      gutter: 0
    });
  }

}).call(this);
